version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      nuget:
        patterns:
          - "*"
        exclude-patterns:
          - "*xunit*"
          - "*verify*"
          - "BenchmarkDotNet"
          - "*coverlet*"
          - "*GitHubActionsTestLogger*"
          - "*Test.Sdk*"
      nuget-testing:
        patterns:
          - "*xunit*"
          - "*verify*"
          - "BenchmarkDotNet"
          - "*coverlet*"
          - "*GitHubActionsTestLogger*"
          - "*Test.Sdk*"

  - package-ecosystem: "npm"
    directory: "/src/PaperMalKing/ClientApp"
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns:
          - "*"