---
name: Setup .NET
description: Setup .NET with specified version, but checks if specified version is already installed on the runner

inputs:
  dotnet-version:
    description: Version of .NET to install
    required: true
  include-prerelease:
    description: Allow pre-release version of .NET to be installed
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Check if specified version of .NET is already installed
      id: versionCheck
      shell: bash
      run: |
        case "$(dotnet --version)" in
        "${{ inputs.dotnet-version }}") echo "::set-output name=is-dotnet-version-preinstalled::true";;
        *) echo "::set-output name=is-dotnet-version-preinstalled::false";;
        esac

    - name: Install .NET SDK
      if: ${{ steps.versionCheck.outputs.is-dotnet-version-preinstalled == 'false'}}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        include-prerelease: ${{ inputs.include-prerelease }}