name: .NET build

on: 
  workflow_dispatch:
  
  push:
    branches: 
      - master
      - v2
      - release/v2
  pull_request:
    branches:
      - master
      - v2
      - release/v2

jobs: 
  build:
    env:
      DOTNET_NOLOGO: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install deps
        run: dotnet restore
      - name: Build projects
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
