name: Comment when something in PaperMalKing.Database project changes

on:
  pull_request:
    branches:
      - dev
      - master
      - release/*
      - main
    types: [opened, reopened]
    paths:
      - '**/PaperMalKing.Database/**'

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: Looks like you changed something in PaperMalKing.Database project. Make sure to run EF core tool to optimize model.